spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/database}
spring.datasource.username=user
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}